CREATE TABLE IF NOT EXISTS perk (
	id SERIAL NOT NULL,
	description VARCHAR(250) NOT NULL,
	is_positive BOOLEAN NOT NULL,
	additional_info VARCHAR(250),
	tier VARCHAR(2),	
	times_won BIGINT,
	times_lost BIGINT
);

INSERT INTO perk (description, is_positive, additional_info) 
VALUES 
	('Earn U$300 everyday, for one year', TRUE, NULL),
	('Make someone who knows you fall in love with you', TRUE, NULL),
	('Become immortal for 10 days', TRUE, NULL),
	('Become really good at something you have zero knowledge about', TRUE, NULL),
	('Go back to when you were 15 knowing everything you know today', TRUE, NULL),
	('Earn two raises at your job', TRUE, NULL),
	('Earn a promotion at your job', TRUE, NULL),
	('Have sex with someone (it can be anyone in the world), for one week, anytime you want', TRUE, NULL),
	('Earn U$10k instantly', TRUE, NULL),
	('Become friends with your idol', TRUE, NULL),
	('Meet your idol', TRUE, NULL),
	('Earn U$50k instantly', TRUE, NULL),
	('Have your next month''s credit card bill paid', TRUE, NULL),
	('Win a all-inclused trip to anywhere in the world for one week', TRUE, NULL),
	('Make someone instantly lose their job', TRUE, NULL),
	('Eat anything you want for free for one month', TRUE, NULL),
	('Three more seasons of your favorite TV series. They''ll be as good as it was before', TRUE, NULL),
	('Become really good at any musical instrument', TRUE, NULL),
	('Earn one year of salary without having to work', TRUE, NULL),
	('You can talk with someone who already died for one day', TRUE, NULL),
	('Die older than 100 years old, if you want', TRUE, NULL),
	('Talk to God, or discover if there is one', TRUE, NULL),
	('You can now talk with your pets', TRUE, NULL),
	('Your child will earn a Nobel at 90 years old', TRUE, NULL),
	('Win an small-sized house/apartment', TRUE, NULL),
	('Have a 50% discount on any car you want', TRUE, NULL),
	('Drug effects last longer and do no harm to your body', TRUE, NULL),
	('Your death will traumatize your entire family', FALSE, NULL),
	('You will die in a vehicle accident (crash or ran over), but you don''t know when', FALSE, NULL),
	('The person you love the most will die in front of you, but you don''t know when', FALSE, 'It will in a accident'),
	('You instantly lose your car/house (or the most expensive thing you have) to the government', FALSE, NULL),
	('You instantly lose your car/house to the government', FALSE, 'If you don''t have neighter, it''s the most expensive thing you own'),
	('Instantly have a $10k debt', FALSE, NULL),
	('All your SOs will cheat on you one day', FALSE, NULL),
	('Lose your job', FALSE, NULL),
	('Can''t have sex for one year', FALSE, NULL),
	('Feel the worst physical pain you had again', FALSE, NULL),
	('Get shot in the leg', FALSE, 'You won''t die'),
	('Have sex with the opposite gender you are attracted to', FALSE, NULL),
	('Drown but get saved in the very last second', FALSE, NULL),
	('Can''t sleep for 3 days', FALSE, NULL),
	('See the year you die', FALSE, NULL),
	('Get convicted to 1 year of prison for a crime you did not commit', FALSE, NULL),
	('Become homeless for one week ', FALSE, 'you can''t sleep at someone''s house'),
	('Lose one hand or one foot, you decide', FALSE, NULL),
	('Have your phone stolen and thieves know how to unlock it', FALSE, NULL),
	('Have your incognito search history leaked', FALSE, NULL),
	('Have your high school/college degree revoked', FALSE, NULL),
	('Become unemployed for 3 months', FALSE, NULL),
	('The next plane you take will crash', FALSE, NULL),
	('Become paraplegic for two weeks', FALSE, NULL),
	('Lose one hand', FALSE, NULL),
	('Become blind for one month', FALSE, NULL),
	('Have a EXTREMELY painful headache right after you have sex for the rest of your life', FALSE, NULL),
	('You will sneeze every minute for the rest of your life', FALSE, 'It stops temporarily when you are asleep')